# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userfriends',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='userfriends',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requests_given',
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='finder.User'),
        ),
        migrations.DeleteModel(
            name='UserFriends',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='recieved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_recieved', to='finder.User'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='finder.User'),
        ),
    ]
